Repository X11Libre/xserver, pull requests merged in 2025-07, with the labels that each got.

#309 xf86vidmode: fix result copying in ProcVidModeGetMonitor()
  Xext/vidmode.c
Labels: bug

#307 xfree86: loadmod: locally scope the errtype variable
  hw/xfree86/loader/loadmod.c
Labels: janitor

#292 xfree86: compat: consolidate logging
  hw/xfree86/compat/README
  hw/xfree86/compat/clientexception.c
  hw/xfree86/compat/log.c
  hw/xfree86/compat/meson.build
  hw/xfree86/compat/nvidiabug.c
  hw/xfree86/compat/xf86_compat.h
Labels: janitor

#333 namespace: drop unused winIsRoot()
  Xext/namespace/hook-windowproperty.c
Labels: janitor

#344 glx: drop including dix-config.h from internal includes
  glx/glxcontext.h
  glx/glxdrawable.h
  glx/glxext.h
  glx/glxscreens.h
  glx/glxserver.h
  glx/glxutil.h
  glx/indirect_table.c
  glx/singlesize.h
  glx/unpack.h
  glx/vndserver_priv.h
  glx/vndservervendor.h
Labels: janitor

#373 glamor: Use EGL_LINUX_DMA_BUF_EXT to create GBM bo EGLImages
  glamor/glamor_egl.c
Labels: nvidia

#410 dix: add buffer helper for rpc payload assembly
  dix/meson.build
  dix/rpcbuf.c
  dix/rpcbuf_priv.h
Labels: janitor

#422 bigreq: declare reply struct where needed
  Xext/bigreq.c
Labels: janitor

#429 vidmode: fix ProcVidModeGetDotClocks() reply size computation
  Xext/vidmode.c
Labels: bug

#427 dix: rpcbuf: add x_rpcbuf_write_string_0t_pad()
  dix/rpcbuf.c
  dix/rpcbuf_priv.h
Labels: janitor

#411 compext: declare variables when needed
  composite/compext.c
Labels: janitor

#414 include: drop obsolete WriteReplyToClient() macro
  doc/Xserver-spec.xml
  include/dix.h
Labels: janitor

#437 dix: add WriteRpcbufToClient()
  dix/dix_priv.h
Labels: janitor

#438 dix: rpcbuf: add getter for 4-byte units needed to store buffer contents
  dix/rpcbuf_priv.h
Labels: janitor

#439 os: osdep: add macro for compile-time type size assert
  os/osdep.h
Labels: janitor

#448 xfree86: fix xf86I2CBusInit() prototype
  hw/xfree86/i2c/xf86i2c.c
  hw/xfree86/i2c/xf86i2c.h
Labels: janitor

#450 fbdevhw: fix const char arguments
  hw/xfree86/fbdevhw/fbdevhw.c
  hw/xfree86/fbdevhw/fbdevhw.h
Labels: janitor

#451 .github: bump xts to current master
  .github/scripts/install-prereq.sh
  .github/scripts/util.sh
Labels: CI

#453 xfree86: i2c: constify I2CBusRec::name
  hw/xfree86/i2c/xf86i2c.h
Labels: janitor

#171 Remove libselinux1-dev
  .github/scripts/ubuntu/install-pkg.sh
Labels: janitor, CI

#363 dix: drop using HAVE_DIX_CONFIG_H
  dix/generate-atoms
  randr/randrstr.h
Labels: janitor

#433 shape: consolidate reply assembly via x_rpcbuf_t
  Xext/shape.c
Labels: janitor

#417 Fix rootDepth not being inited
  Xext/xcmisc.c
Labels: janitor

#444 meson.build: Enabled udev for FreeBSD.
  meson.build
Labels: enhancement

#471 meson.build: Don't silently change the user's option regarding udev s…
  meson.build
  meson_options.txt
Labels: code-cleanup

#473 .github: delete old workflows
  .github/workflows/tidy-up-auto.yml
Labels: CI

#475 os: move X_NOTIFY_* defines to separate header
  include/fd_notify.h
  include/meson.build
  include/os.h
  os/ospoll.c
Labels: janitor

#489 os: xdmcp: fix missing include of <X11/Xdmcp.h>
  os/osdep.h
  os/xdmcp.h
Labels: bug

#476 mi: use %lu instead of %zu in ErrorF() call
  mi/mieq.c
Labels: code-cleanup

#426 xv: inline SWrite*Reply() functions
  Xext/xvdisp.c
Labels: janitor

#479 CI: add windows / mingw support
  .github/scripts/mingw32/cross-i686-w64-mingw32.txt
  .github/scripts/mingw32/cross-prereqs-build.sh
  .github/workflows/build-xserver.yml
Labels: code-cleanup
