Repository X11Libre/xserver, pull requests merged in 2025-06, with the labels that each got.

#56 Fix incorrect power of two operator
  hw/xnest/xcb.c
  os/connection.c
Labels: bug

#77 hw/xnest/Events: fix uninitialized BoxRec
  hw/xnest/Events.c
Labels: janitor

#165 .github: workflow for building Xservers and some drivers
  .github/scripts/compile-drivers.sh
  .github/scripts/conf.sh
  .github/scripts/install-prereq.sh
  .github/scripts/ubuntu/install-pkg.sh
  .github/scripts/ubuntu/remove-unused-pkg.sh
  .github/scripts/util.sh
  .github/workflows/build-xserver.yml
Labels: enhancement

#159 fix drivers list in README
  README.md
Labels: janitor

#178 dix: delete unused structure
  dix/property.c
Labels: janitor, DIX

#198 README.md: add driver release tags
  README.md
Labels: documentation

#15 glx: fix correct sizeof GL unsigned int
  glx/rensize.c
Labels: janitor

#225 randr: fix memleak in provider property update
  randr/rrproviderproperty.c
Labels: bug

#247 rootless: fix missing include of dix/screen_hooks_priv.h
  miext/rootless/rootlessWindow.h
Labels: bug, xquartz

#227 glamor: Enable dmabuf_capable for Zink
  glamor/glamor_egl.c
Labels: enhancement, modesetting

#271 .github: limit pipeline permissions to read-only
  .github/workflows/build-xserver.yml
Labels: CI
