Repository X11Libre/xserver, pull requests merged in 2025-08, with the labels that each got.

#465 kdrive: move ephyr build option check into kdrive's meson.build
  hw/kdrive/meson.build
  hw/meson.build
  meson.build
Labels: janitor

#519 os: connection: simplify connection error sending
  os/connection.c
Labels: janitor

#570 glamor: don't redefine ALIGN macro if it exists
  glamor/glamor_utils.h
Labels: janitor

#572 glx: fix duplicate typedef
  glx/glxscreens.h
  include/glx_extinit.h
Labels: janitor

#571 xfree86: drm_platform: fix warning on potentially unitialized variable
  hw/xfree86/os-support/shared/drm_platform.c
Labels: janitor

#619 render: picture: make PictFormatShort equal to pixman_format_code_t
  render/picture.h
Labels: janitor

#628 os: io: FlushClient() consolidate error/abort code path
  os/io.c
Labels: janitor

#617 os: io: fix NULL output buffer after FlushClient()
  os/io.c
Labels: bug

#659 Xext: saver: drop duplicate ScreenPtr retrival in SendScreenSaverNoti…
  Xext/saver.c
Labels: janitor

#652 dix: fix int mismatches related to MakeAtom()
  dix/atom.c
  dix/dix_priv.h
  randr/rrmonitor.c
  xkb/xkmread.c
Labels: janitor

#666 namespace: allow "namespace" config directive instead of "container"
  Xext/namespace/config.c
Labels: janitor

#667 treewide: fix serverGeneration int type mismatch
  Xext/panoramiX.c
  Xext/sleepuntil.c
  Xext/xvmain.c
  dix/dixfonts.c
  dix/globals.c
  dri3/dri3.c
  glamor/glamor_font.c
  glx/glxext.c
  hw/kdrive/src/kdrive.c
  hw/kdrive/src/kdrive.h
  hw/kdrive/src/kxv.c
  hw/xfree86/dri/dri.c
  hw/xfree86/drivers/video/modesetting/dri2.c
  hw/xfree86/drivers/video/modesetting/driver.h
  hw/xfree86/modes/xf86RandR12.c
  hw/xfree86/os-support/linux/int10/linux.c
  hw/xquartz/applewm.c
  hw/xquartz/xpr/xprFrame.c
  hw/xwin/win.h
  hw/xwin/winallpriv.c
  hw/xwin/winclipboardwrappers.c
  hw/xwin/winglobals.c
  hw/xwin/winmultiwindowwm.c
  hw/xwin/winwndproc.c
  include/misc.h
  miext/rootless/rootlessWindow.c
  os/xdmcp.c
  pseudoramiX/pseudoramiX.c
  randr/randr.c
  render/picture.c
  xkb/ddxBeep.c
Labels: janitor

#686 panoramiX: XineramaGetImageData(): simplify the loop
  Xext/panoramiX.c
Labels: janitor

#676 randr: use x_rpcbuf_t in ProcRRGetProviderProperty()
  randr/rrproviderproperty.c
Labels: janitor

#677 dix: use x_rpcbuf_t in ProcGetProperty()
  dix/property.c
Labels: janitor

#680 dix: fix int type mismatch on CURSOR_REC_SIZE and CURSOR_BITS_SIZE
  include/cursorstr.h
Labels: janitor

#689 treewide: use use x_rpcbuf_wsize_units() instead of rpcbuf.wpos
  Xext/xvdisp.c
  xkb/xkb.c
Labels: janitor

#720 xfixes: cursor: use x_rpcbuf_t and X_SEND_REPLY_WITH_RPCBUF()
  xfixes/cursor.c
Labels: janitor

#718 dix: rpcbuf: add x_rpcbuf_write_counted_string_pad()
  dix/rpcbuf_priv.h
Labels: janitor

#704 panoramix: XineramaGetImageData() split out code inside the big loop
  Xext/panoramiX.c
Labels: janitor

#695 xf86bigfont: ProcXF86BigfontQueryFont(): use x_rpcbuf_t
  Xext/xf86bigfont.c
Labels: janitor

#807 Xext: xres: fix XResQueryClientResources request
  Xext/xres.c
Labels: bug

#691 modesetting: Overhaul and fix cursor probing.
  hw/xfree86/drivers/video/modesetting/driver.c
  hw/xfree86/drivers/video/modesetting/driver.h
  hw/xfree86/drivers/video/modesetting/drmmode_display.c
  hw/xfree86/drivers/video/modesetting/drmmode_display.h
  include/meson.build
Labels: bug, hardware-cursor
